### ISSUE TITLE
More icons.

### ISSUE THREAD

**Issue by ctrlaltvikas** [qieguo2016/iconoo#1]
Can't we add more icons to this amazing collection. Say using double quotes or minus or % or $ ?

**Comment by qieguo2016** [comment]
I am sorry that I don't know what you mean. Now the icons are drew by `border` or `box-shadow`. Yes of course we can add words to icons via `content`, but it is hard to draw the shape you want.

**Comment by qieguo2016** [comment]
Hello!
Maybe you can describe what icons you want next time.
